# Generated by Django 4.0.1 on 2022-01-18 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('customer_xid', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(blank=True, default='12345678', max_length=200, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('withdrawn_by', models.CharField(blank=True, max_length=255, null=True)),
                ('deposited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('deposited_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('reference_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(default='disable', max_length=255)),
                ('enable_at', models.DateTimeField(blank=True, null=True)),
                ('disable_at', models.DateTimeField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, default=0)),
                ('owned_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
